//propagating exceptions via std::future square root example 